name: pipeline

on: [push, pull_request]

jobs:
    luacheck:
        name: luacheck
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: Setup Lua
          uses: leafo/gh-actions-lua@v5

        - name: Setup Lua Rocks
          uses: leafo/gh-actions-luarocks@v2

        - name: Install luacheck
          run: luarocks install luacheck

        - name: validate code
          run: luacheck --config .luacheckrc .

    wowi_publish:
        name: wowinterface publish
        runs-on: ubuntu-latest
        needs: luacheck
        if: contains(github.ref, 'refs/tags')
        steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: wowinterface release
          env:
            WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          run: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

        - name: get version
          id: vars
          run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

        - name: create github release
          id: create_release
          uses: actions/create-release@latest
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ steps.vars.outputs.tag }}
            release_name: ${{ steps.vars.outputs.tag }}
            draft: false
            prerelease: false

        - name: upload github release
          uses: actions/upload-release-asset@latest
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./.release/sInterface-${{ steps.vars.outputs.tag }}.zip
            asset_name: sInterface-${{ steps.vars.outputs.tag }}.zip
            asset_content_type: application/zip
